// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WorldNews
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("category")]
        public Category Category { get; set; }

        [JsonProperty("articleCount")]
        public long ArticleCount { get; set; }

        [JsonProperty("articles")]
        public Article[] Articles { get; set; }
    }

    public partial class Article
    {
        [JsonProperty("category")]
        public Category Category { get; set; }

        [JsonProperty("website")]
        public Website Website { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("pubDate")]
        public string PubDate { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }
    }

    public enum Category { Technology };

    public enum Website { LatestFromTechRadarUsInComputingNews, LatestNews, NytTechnology, TheHackerNews, TheVerge, Wired };
}
